export const MAX_COLS = 10;

export const ROLES = [
	{ id: 'rp', text: 'Representative' },
	{ id: 'mg', text: 'Manager' },
];

// key is important
export const FLAGS = {
	fg: { id: 'fg', title: 'Flagged', color: 'info' },
	pn: { id: 'pn', title: 'Poor Notes', color: 'secondary' },
	cb: { id: 'cb', title: 'Call Back', color: 'warning' },
	ug: { id: 'ug', title: 'Urgent', color: 'success' },
	es: { id: 'es', title: 'Escalation', color: 'danger' },
};

export const HEADERS = {
	st: {
		id: 'st',
		text: 'Started',
		size: 2,
		field: 'insertDate',
		type: 'DateTime',
		sortable: true,
		dateRange: 'past',
	},
	lu: {
		id: 'lu',
		text: 'Updated',
		size: 2,
		field: 'updateDate',
		type: 'DateTime',
		sortable: true,
		dateRange: 'past',
	},
	lt: {
		id: 'lt',
		text: 'Touched',
		size: 2,
		field: 'lastTouched',
		type: 'DateTime',
		sortable: true,
		dateRange: 'past',
	},
	ab: {
		id: 'ab',
		text: 'Assigned By',
		size: 3,
		field: 'assignedByName',
		type: 'Person',
		sortable: true,
		align: 'flex-start',
	},
	ca: {
		id: 'ca',
		text: 'Case',
		size: 1,
		field: 'caseId',
		type: 'Case',
		align: 'flex-start',
		mobile: true,
	},
	de: {
		id: 'de',
		text: 'Description',
		size: 4,
		field: 'problem',
		type: 'Summary',
		align: 'flex-start',
	},
	as: {
		id: 'as',
		text: 'Assigned',
		size: 2,
		field: 'assignedDate',
		type: 'DateTime',
		sortable: true,
		dateRange: 'past',
	},
	du: {
		id: 'du',
		text: 'Due',
		size: 2,
		field: 'dueDate',
		type: 'DateTime',
		sortable: true,
		dateRange: 'future',
	},
	pr: {
		id: 'pr',
		text: 'Product',
		size: 3,
		field: 'product',
		type: 'Product',
		sortable: true,
	},
	cc: {
		id: 'cc',
		text: 'Call(Back)s',
		size: 1,
		field: 'callCount',
		type: 'CallCount',
		sortable: true,
	},
	ss: {
		id: 'ss',
		text: 'Status',
		size: 2,
		field: 'status',
		type: 'Status',
		sortable: true,
		mobile: true,
	},
};

export const REMINDERS = {
	'0d': { value: '0d', label: 'None' },
	'1d': { value: '1d', label: 'Everyday' },
	'2d': { value: '2d', label: 'Every 2 days' },
	'3d': { value: '3d', label: 'Every 3 days' },
	'4d': { value: '4d', label: 'Every 4 days' },
	'5d': { value: '5d', label: 'Every 5 days' },
	'6d': { value: '6d', label: 'Every 6 days' },
	'7d': { value: '7d', label: 'Every 7 days' },
	'2w': { value: '2w', label: 'Every 2 Weeks' },
	'1M': { value: '1M', label: 'Every Month' },
	'1Q': { value: '1Q', label: 'Every 3 Months' },
};

export const DATE_RANGES = [
	{ id: 'all', value: '', title: 'All', range: 'both' },
	{ id: 'lw', value: 'last_week', title: 'Last Week', range: 'past' },
	{ id: 'yd', value: 'yesterday', title: 'Yesterday', range: 'past' },
	{ id: 'td', value: 'today', title: 'Today', range: 'both' },
	{ id: 'tr', value: 'tomorrow', title: 'Tomorrow', range: 'future' },
	{ id: 'tw', value: 'this_week', title: 'This Week', range: 'both' },
	{ id: 'nw', value: 'next_week', title: 'Next Week', range: 'future' },
];

export const STATUSES = {
	ut: {
		id: 'ut',
		text: 'Untouched',
		reminder: '1d',
		color: '#8e96db',
		active: true,
		selectable: false,
	},
	dt: {
		id: 'dt',
		text: 'Due Today',
		reminder: '0d',
		color: '#e5d3e5',
		active: true,
		selectable: false,
	},
	pd: {
		id: 'pd',
		text: 'Past Due',
		reminder: '0d',
		color: '#d3002d',
		active: true,
		selectable: false,
	},
	ud: {
		id: 'ud',
		text: 'Updated',
		reminder: '0d',
		color: '#c1a55d',
		active: true,
		selectable: false,
	},
	cs: {
		id: 'cs',
		text: 'Follow Up',
		reminder: '0d',
		color: '#4626a5',
		active: true,
		selectable: false,
	},
	ro: {
		id: 'ro',
		text: 'Reopened',
		reminder: '0d',
		color: '#ff80ff',
		active: true,
		selectable: false,
	},
	re: {
		id: 're',
		text: 'Researching',
		reminder: '2d',
		color: '#6e96b2',
		active: true,
		selectable: true,
	},
	ra: {
		id: 'ra',
		text: 'Reassigned',
		reminder: '5d',
		color: '#7b90c6',
		active: true,
		selectable: true,
	},
	rs: {
		id: 'rs',
		text: 'Resolved',
		reminder: '5d',
		color: '#319b1f',
		active: false,
		selectable: true,
	},
	cc: {
		id: 'cc',
		text: 'Closed',
		reminder: '5d',
		color: '#319b1f',
		active: false,
		selectable: false,
	},
	es: {
		id: 'es',
		text: 'Escalated',
		reminder: '7d',
		color: '#e0bfb5',
		active: true,
		selectable: true,
	},
	pf: {
		id: 'pf',
		text: 'Pending Fix',
		reminder: '2w',
		color: '#bee26f',
		active: false,
		selectable: true,
	},
};
